//go:build linux

package supervisor

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
)

// cgroupHandle bundles an open cgroup directory fd with a cleanup
// closure that removes the cgroup directory after the child exits.
// The Fd field is -1 when the cgroup path is unavailable (no cgroup v2,
// no write permission, missing controllers) and the caller falls back
// to prlimit-only enforcement.
type cgroupHandle struct {
	Fd      int
	Cleanup func()
}

// noopCgroupHandle is the fallback returned when cgroup v2 isn't
// available. Fd=-1 tells the supervisor to skip SysProcAttr.UseCgroupFD;
// the prlimit path still runs.
var noopCgroupHandle = cgroupHandle{Fd: -1, Cleanup: func() {}}

// prepareCgroup tries to create a child cgroup at
// <root>/reactor/<runID> with memory.max + pids.max set from lim, then
// returns a handle to its fd. Any failure (not a cgroup v2 mount, no
// write permission, controllers not delegated) returns the noop handle
// + logs a warning. The supervisor never aborts on cgroup failure.
func prepareCgroup(log *slog.Logger, runID string, lim ResourceLimits) cgroupHandle {
	if lim.CgroupRoot == "" {
		return noopCgroupHandle
	}
	lim = lim.withDefaults()

	if !isCgroupV2(lim.CgroupRoot) {
		log.Debug("cgroup: skipping (not cgroup v2)", "root", lim.CgroupRoot)
		return noopCgroupHandle
	}

	// Ensure the parent "reactor" cgroup exists + has memory + pids
	// controllers enabled in subtree_control. This is idempotent.
	parent := filepath.Join(lim.CgroupRoot, "reactor")
	if err := os.MkdirAll(parent, 0o755); err != nil {
		log.Warn("cgroup: parent mkdir failed; falling back to prlimit-only",
			"path", parent, "err", err)
		return noopCgroupHandle
	}
	// Best-effort enable controllers. If subtree_control doesn't exist
	// or we can't write it, the child cgroup may lack controllers; we
	// still try the child path and let mkdir/limit-set fail loudly if
	// the controllers are unavailable.
	_ = os.WriteFile(filepath.Join(parent, "cgroup.subtree_control"),
		[]byte("+memory +pids"), 0o644)

	child := filepath.Join(parent, sanitiseRunID(runID))
	if err := os.MkdirAll(child, 0o755); err != nil {
		log.Warn("cgroup: child mkdir failed; falling back to prlimit-only",
			"path", child, "err", err)
		return noopCgroupHandle
	}

	cleanup := func() {
		// Move any straggling pids back to the parent before rmdir; the
		// kernel rejects rmdir on a non-empty cgroup. v2 doesn't allow
		// writing to a child's cgroup.procs after the leader exits in
		// the happy path, so this is best-effort.
		os.Remove(filepath.Join(child, "cgroup.events")) // ignore err
		_ = os.Remove(child)
	}

	if lim.MemoryMaxBytes > 0 {
		if err := os.WriteFile(filepath.Join(child, "memory.max"),
			[]byte(strconv.FormatUint(lim.MemoryMaxBytes, 10)), 0o644); err != nil {
			log.Warn("cgroup: memory.max write failed (controller likely undelegated); falling back",
				"err", err)
			cleanup()
			return noopCgroupHandle
		}
	}
	if lim.MaxProcesses > 0 {
		if err := os.WriteFile(filepath.Join(child, "pids.max"),
			[]byte(strconv.FormatUint(lim.MaxProcesses, 10)), 0o644); err != nil {
			log.Warn("cgroup: pids.max write failed (controller likely undelegated); falling back",
				"err", err)
			cleanup()
			return noopCgroupHandle
		}
	}

	fd, err := syscall.Open(child, syscall.O_RDONLY|syscall.O_DIRECTORY, 0)
	if err != nil {
		log.Warn("cgroup: open dir fd failed; falling back to prlimit-only",
			"path", child, "err", err)
		cleanup()
		return noopCgroupHandle
	}
	return cgroupHandle{
		Fd: fd,
		Cleanup: func() {
			syscall.Close(fd)
			cleanup()
		},
	}
}

// isCgroupV2 reports whether the given mount root is a cgroup v2
// hierarchy. Tests both the canonical sentinel file (cgroup.controllers
// exists at the v2 root) and that the path is a directory.
func isCgroupV2(root string) bool {
	info, err := os.Stat(root)
	if err != nil || !info.IsDir() {
		return false
	}
	if _, err := os.Stat(filepath.Join(root, "cgroup.controllers")); err != nil {
		return false
	}
	return true
}

// sanitiseRunID strips any path-traversal funkiness from a run id so it
// can be used directly as a cgroup directory component. Run ids are
// generated by the journal but we still defend against malformed input
// in the data path that talks to /sys.
func sanitiseRunID(runID string) string {
	if runID == "" {
		return "unknown"
	}
	clean := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			return r
		case r == '_' || r == '-':
			return r
		default:
			return '_'
		}
	}, runID)
	if len(clean) > 64 {
		clean = clean[:64]
	}
	return clean
}

// applyCgroupToSysProcAttr is a small adapter so supervisor.go doesn't
// need build-tagged access to syscall.SysProcAttr.UseCgroupFD (that
// field exists on Linux only).
func applyCgroupToSysProcAttr(attr *syscall.SysProcAttr, h cgroupHandle) {
	if h.Fd < 0 {
		return
	}
	attr.UseCgroupFD = true
	attr.CgroupFD = h.Fd
}

// closeCgroupHandle exists so the non-Linux stub can expose an
// equivalent no-op without importing this file's types directly.
func closeCgroupHandle(h cgroupHandle) {
	if h.Cleanup != nil {
		h.Cleanup()
	}
}

// String for log readability; kept here so cgroup_other.go can mirror.
func (h cgroupHandle) String() string {
	if h.Fd < 0 {
		return "noop"
	}
	return fmt.Sprintf("fd=%d", h.Fd)
}
